# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: La Vulcanizadora
email: your-email@example.com
description: >-
    We are a creative laboratory in Cinema, Visual Arts, and Expanded Theater.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lavulcanizadora.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username: lavulcanizadora

# Build settings
plugins:
    - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
    projects:
        output: true
        order:
            - yarokamena.md
            - openmountain.md
            - therebirthofcarare.md
            - nohillwithoutsun.md
            - openmountainaspectratio.md
            - planosmonteymontaje.md
            - fu.md
            - arevolutionthathasnotbeenyet.md
            - wewerealwayshereno.md
            - pisostermicos.md
            - archiviolitica.md
            - welcomeinterplanetaryandsiderealspaceconquerors.md
            - yvuuhzaokaina.md
            - cortacabezas.md
            - marandua.md
            - theplacesspeak.md
            - whenthesunriseslikearedbomb.md

    proyectos:
        output: true
        order:
            - yarokamena.md
            - abrirmonte.md
            - elrenacerdelcarare.md
            - nohaymontesinsol.md
            - abrirmonterelaciondeaspecto.md
            - planosmonteymontaje.md
            - fu.md
            - unarevolucionqueaunnohasido.md
            - siemprehemosestadoaquino.md
            - pisostermicos.md
            - archiviolitica.md
            - bienvenidosconquistadoresinterplanetarios.md
            - yvuuhzaokaina.md
            - cortacabezas.md
            - marandua.md
            - hablanloslugares.md
            - cuandoelsolamaneces.md

defaults:
    - scope:
          path: "_projects"
      values:
          permalink: /en/projects/:path/
          layout: "project"
          language: "en"

    - scope:
          path: "_proyectos"
      values:
          permalink: /es/proyectos/:path/
          layout: "project"
          language: "es"
