---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: media
  label: media
- type: textarea
  name: details
  label: details
- type: field_group_list
  name: images
  label: images
  fields:
  - name: images
    type: file
    config:
      maxSize: 64
    label: images
- name: cover
  type: text
  config:
    required: false
  label: cover
pages:
- _proyectos/yarokamena.md
