---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: media
  label: media
- type: textarea
  name: details
  label: details
- type: field_group_list
  name: images
  label: images
  fields:
  - name: path
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: false
      schema:
        format: markdown
    label: path
- name: cover
  type: text
  config:
    required: false
  label: cover
